proto_library(
    name = "list_all_beers_proto",
    srcs = [ "list_all_beers.proto" ],
    deps = [
        "//beer_service_protos/domain:beer_proto"
    ],
    visibility = [ "//beer_service_protos:__pkg__" ]
)

proto_library(
    name = "get_beer_by_id_proto",
    srcs = [ "get_beer_by_id.proto" ],
    deps = [
        "//beer_service_protos/domain:beer_proto"
    ],
    visibility = [ "//beer_service_protos:__pkg__" ]
)


proto_library(
    name = "create_beer_proto",
    srcs = [ "create_beer.proto" ],
    deps = [
        "//beer_service_protos/domain:beer_proto"
    ],
    visibility = [ "//beer_service_protos:__pkg__" ]
)
